parameters:

services:
  happyr.translation.loader:
    class: Happyr\TranslationBundle\Translation\Loader
    tags:
      - { name: 'translation.loader', alias: 'phps' }

  happyr.translation.dumper:
    class: Happyr\TranslationBundle\Translation\Dumper
    tags:
      - { name: 'translation.dumper', alias: 'phps' }

  # Custom data_collector to use our own template
  happyr.translation.data_collector:
    class: Symfony\Component\Translation\DataCollector\TranslationDataCollector
    arguments: [ '@?translator.data_collector' ]
    tags:
      - { name: 'data_collector', template: "@HappyrTranslation/Profiler/translation", id: "translation", priority: 200 }

  happyr.translation.service.loco:
    class: Happyr\TranslationBundle\Service\Loco
    arguments:
      - '@happyr.translation.http_adapter'
      - '@happyr.translation.filesystem'
      - ~
      - ~

  happyr.translation.filesystem:
    class: Happyr\TranslationBundle\Translation\FilesystemUpdater
    arguments:
      - '@happyr.translation.loader'
      - '@happyr.translation.dumper'
      - ~
    tags:
      - { name: kernel.event_listener, event: kernel.terminate, method: onTerminate, priority: -20 }
      - { name: kernel.event_listener, event: console.terminate, method: onTerminate, priority: -20 }


  happyr.translation.http_adapter.guzzle5:
    class: Happyr\TranslationBundle\Http\Guzzle5Adapter
    public: false

  happyr.translation.http_adapter.guzzle6:
    class: Happyr\TranslationBundle\Http\Guzzle6Adapter
    public: false
